name: Python Test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.3"


    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    
